modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="vl_abyss"
version="1.2.0"
displayName="SSMP | S1"
displayURL="https://discord.gg/vlmp"
logoFile="logo.png"
credits="https://discord.gg/vlmp"
authors="SSMP | S1"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.vl_abyss]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="AFTER"
side="BOTH"


[[dependencies.vl_abyss]]
modId="use_compiled_mods"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"
[[dependencies.vl_abyss]]
modId="curios_api"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"
[[dependencies.vl_abyss]]
modId="patchouli"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"
[[dependencies.vl_abyss]]
modId="geckolib"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"
[[dependencies.vl_abyss]]
modId="playeranimator"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"
[[dependencies.vl_abyss]]
modId="jei"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"


# Start of user code block dependencies configuration
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
# End of user code block dependencies configuration
